const START_AS_PADAVAN = "START_AS_PADAVAN";
const START_AS_MENTOR = "START_AS_MENTOR";
const SESSION_EXPIRED = "SESSION_EXPIRED";

module.exports = {
  START_AS_MENTOR,
  START_AS_PADAVAN,
  SESSION_EXPIRED
};
